version: "3"
services:
  menus:
    container_name: andrewpoon/reservly:menus
    restart: always
    build: .
    ports:
      - "80:3003"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - ./db
    ports:
      - "27017:27017" 
    command: "mongod --smallfiles"